" Fuzhou's configuration file for VIM.
" This configuration should work on both Vim and Nvim (best effort),
" verified mostly on Linux and Windows. Mac should work but may not test
" sufficiently. Let me know if I missed something.
"
" Note that some folders/paths may reflect settings on my own machine.
" May have to modify a bit.

set nocompatible
set guioptions-=T

" File encodings for working on Windows (CP936), Linux/Mac (UTF-8) 
set fileencodings=""
set fileencoding=""
if has("win32")
    set bomb
    set fileencodings=ucs-bom,cp936,utf8,ucs-2,utf-16,utf-16le
    if has("nvim")
        set encoding=utf-8
        set termencoding=utf-8
    else
        set encoding=cp936
        set termencoding=cp936
    endif
else
    set fileencodings=ucs-bom,utf8,cp936,ucs-2,utf-16,utf-16le
    set encoding=utf8
    set termencoding=utf8
    set visualbell
endif

" Configure GUI
if has("gui_running")
    " Unlike vim, neovim does not use guifont, thus it does not
    " recognize options like guifont. It impacts editors like vimr.
    if has("unix") && !has('nvim')
        if system('uname') =~ 'Darwin'
            set guifont=Monaco:h13
        else
            set guifont=Monospace\ 12
        endif
    endif
endif


" Always enable true color. No worry. All my machines support it.
if has("termguicolors")
    let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

" All messages use English so no bogus characters displayed in terminal.
language messages C

" Basic editor look & feel
set showmatch
set ruler
set mouse=a
set modeline
set modelines=5
set number
set backspace=indent,eol,start whichwrap+=<,>,[,]

" Remember line from last edit and jump to it. Useful when editing.
autocmd BufReadPost * if (line("'\"") > 0 && line("'\"") <= line("$")) | exe "normal g'\"" | endif

" Default formatting. Should be suffcicent for most programming language
" developers. Some settings, for example, Linux C code, may need special
" settings. Please set it with autocmd, if needed. See end of
" this configuration for details.
set expandtab
set shiftwidth=4
set incsearch
set hlsearch
set textwidth=72
set colorcolumn=72

au BufNewFile,BufRead *.js  set cindent
au BufNewFile,BufRead *.wsf set autoindent

" ---- Setting for Visual studio 2005
au BufNewFile,BufRead *.csproj set ft=xml
au BufNewFile,BufRead *.csproj set fileencoding=utf8
au BufNewFile,BufRead *.csproj set encoding=utf8
au BufNewFile,BufRead *.csproj set fileencoding=utf8
au BufNewFile,BufRead *.sln set encoding=utf8
au BufNewFile,BufRead *.msh set filetype=msh
au BufNewFile,BufRead *.sif set filetype=dosini

" Powershell
au BufEnter *.ps1 :set ft=ps1
au BufEnter *.ps1 :set cindent

" File open settings
au BufEnter SConscript :set ft=python
au BufEnter *.mm :set ft=objc
au BufEnter *.exs :set ft=elixir

" NOTE: Reading Chinese text does not work well with it, for it treats
" all Chinese characters as spelling errors. I haven't found a good way
" to make two languages living together. Let's just live with it.
au BufEnter *.txt :setlocal spell spelllang=en_us
au BufEnter *.md :setlocal spell spelllang=en_us
au BufEnter *.rst :setlocal spell spelllang=en_us
au BufEnter *.md.txt :setlocal spell spelllang=en_us
au BufEnter *.rst.txt :setlocal spell spelllang=en_us

" Force disable foldmethod by expr. Good for Nvim.
au BufEnter *.rst :setlocal foldmethod=manual

" Data files don't need too many indentions.
au BufEnter *.xml :set shiftwidth=2
au BufEnter *.yaml :set shiftwidth=2
au BufEnter *.yml :set shiftwidth=2
au BufEnter *.json :set shiftwidth=2

" Golang - Let's make sure we meet gofmt settings.
au BufNewFile,BufRead *.go set noexpandtab shiftwidth=8



" My hand written syntax highlighting for Bond file.
au BufNewFile,BufRead *.bond set ft=bond

" Disable ruler in Cygwin environment. TODO Why did we do it?
if has("win32unix")
    set noruler
endif

" File navigation by Netrw
" REF: https://shapeshed.com/vim-netrw/
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_winsize = 20

" ===================================================================
" Plugins, including syntax highlighting and enhancement.
" ===================================================================
" All necessary plug-ins to support better editor experiences.
call plug#begin('~/.vim/bundle')

" Plugins I don't always use. Enable them on demand.
" Plug 'JuliaEditorSupport/julia-vim'
" Plug 'elixir-lang/vim-elixir'
" Plug 'mattonrails/vim-mix'
" Plug 'derekwyatt/vim-scala'
" Plug 'udalov/kotlin-vim'
" Plug 'aklt/plantuml-syntax'
" Plug 'PProvost/vim-ps1'
" Plug 'zah/nim.vim'

" An bug: it always complains g:airline_statusline_funcrefs undefined.
let g:vaxe_enable_airline_defaults=0
Plug 'jdonaldson/vaxe'

" Plug 'yegappan/lsp'

Plug 'rust-lang/rust.vim'
Plug 'fatih/vim-go'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mechatroner/rainbow_csv'
Plug 'janet-lang/janet.vim'

" Let's change our live a bit: Enable LSP for C++. 
" Note: I used to use yegappan/lsp but dropped it later for two reasons:
" 1. It uses Vim9 script. It breaks compatibility with NeoVim.
" 2. (Seems) It relies on lsp server to get symbols in asynchronized
"    way, which causes long delay when coding Zig.
"
" Prabirshrestha/vim-lsp solves all the problems above.
"
" Meanwhile I didnt' enable mattn/vim-lsp-settings because I want to use
" OS package to management installation of lsp servers.
Plug 'prabirshrestha/vim-lsp'
" Plug 'mattn/vim-lsp-settings'

" Themes
" I use themes from  https://github.com/rafi/awesome-vim-colorschemes
" Plug 'joshdick/onedark.vim'

" ===================================================================
" Syntax highlighting
" ===================================================================
" Must put syntax setting here, or vim will exit with code 1 when
" running hg commit. Reasons still unknown. Suggestion comes from
" pathogen Github page.
syntax on
filetype plugin indent on
call plug#end()

if !exists('g:GtkGuiLoaded') && !has("gui_running")
    " Set transparent background for console, but don't do it for
    " Neovim-GTK, as it results in a completely black background.
    au VimEnter * hi Normal guibg=NONE ctermbg=NONE
endif

" Color schemes
" I use only two themes, built-in desert and onedark. Onedark
" is usually used by default but sometimes I need a brighter color.
" Desert looks better in dark theme but needs a small modification to
" get a reasonable SpellBad look and feel. See below for switching.
" 
" I personally still love onedark theme, yet I somethings like desert for a
" comfortable eye-feelings under low screen blightness, especially for
" reading comments. Onedark has a nice color but constract is too low.
"
" So I tweak color of comments for better readability. The color settings
" here is copied from desert color scheme.
colorscheme desert
highlight Normal guibg=#171421
highlight Comment term=bold ctermfg=11 guifg=#6DCEEB
highlight Cursor guibg=blue guibg=yellow
let g:airline_theme="onedark"
if has("win32")
    let g:airline_powerline_fonts=0
else
    let g:airline_powerline_fonts=1
endif

if executable('zls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'zls',
        \ 'cmd': {server_info->['zls']},
        \ 'allowlist': ['zig'],
        \ })
endif

if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd']},
        \ 'allowlist': ['c','cpp'],
        \ })
endif

if executable('rust-analyzer')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rust-analyzer',
        \ 'cmd': {server_info->['rust-analyzer']},
        \ 'allowlist': ['rust'],
        \ })
endif

if executable('haxe-lsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'haxe',
        \ 'cmd': {server_info->['haxe-lsp']},
        \ 'whitelist': ['haxe'],
        \ 'initialization_options': {
        \    'displayServerConfig': {
        \        'env': {},
        \        'path': '/usr/bin/haxe',
        \        'arguments': []
        \    },
        \    'displayArguments': ['compile.hxml']
        \ },
        \ 'workspace_config': {
        \    'haxe': {
        \       'enableDiagnostics': v:true,
        \       'diagnosticsPathFilter': '',
        \       'enableCodeLens': v:true,
        \       'displayPort': 'auto',
        \       'buildCompletionCache': v:true,
        \       'codeGeneration': {},
        \       'format': {}
        \    },
        \ }
    \ })
endif

function! s:on_lsp_buffer_enabled() abort
    " setlocal omnifunc=lsp#complete
    " setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
    nnoremap <buffer> <expr><c-d> lsp#scroll(-4)

    let g:lsp_format_sync_timeout = 1000
    autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')

    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

" TODO Something wrong in zig file binding when writing buffer.
let g:zig_fmt_autosave = 0


" Below are my Windows dev settings. Hope I can reuse them some day.
if has("win32")
    set selectmode="mouse,key"
    set keymodel="startsel,stopsel"
    set backspace=indent,eol,start whichwrap+=<,>,[,]
    au BufNewFile,BufRead *.cpp set makeprg=MSBuild.exe efm=%f(%l):\ %m
    au BufNewFile,BufRead *.c set makeprg=MSBuild.exe efm=%f(%l):\ %m
    au BufNewFile,BufRead *.cs set makeprg=MSBuild.exe efm=%f(%l):\ %m
    au BufNewFile,BufRead *.vbs set makeprg=cscript efm=%f(%l%m
    au BufNewFile,BufRead *.js  set makeprg=cscript efm=%f(%l%m
    au BufNewFile,BufRead *.wsf  set makeprg=cscript efm=%f(%l%m

    if has("gui_running")
        set guifont=consolas:h11
    endif
endif
