set nocompatible
set guioptions-=T

" File encodings for working on both Linux (UTF-8) and Windows (CP936).
set fileencodings=""
set fileencoding=""
if has("win32")
    set bomb
    set fileencodings=ucs-bom,cp936,utf8,ucs-2,utf-16,utf-16le
    if has("nvim")
        set encoding=utf-8
        set termencoding=utf-8
    else
        set encoding=cp936
        set termencoding=cp936
    endif
else
    set fileencodings=ucs-bom,utf8,cp936,ucs-2,utf-16,utf-16le
    set encoding=utf8
    set termencoding=utf8
    set visualbell
endif

" Configure GUI
if has("gui_running")
    " Unlike vim, neovim does not use guifont, thus it does not
    " recognize options like guifont. It impacts editors like vimr.
    if has("unix") && !has('nvim')
        if system('uname') =~ 'Darwin'
            set guifont=Monaco:h13
        else
            set guifont=Monospace\ 12
        endif
    endif
endif


" Always enable true color. No worry. All my machines support it.
if has("termguicolors")
    let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

" All messages use English so no bogus characters in terminal.
language messages C

" Editor look & feel
set showmatch
set ruler
set mouse=a
set modeline
set modelines=5
set number
set backspace=indent,eol,start whichwrap+=<,>,[,]
" Remember line from last edit and jump to it.
autocmd BufReadPost * if (line("'\"") > 0 && line("'\"") <= line("$")) | exe "normal g'\"" | endif

set expandtab
set shiftwidth=4
set incsearch
set hlsearch
set textwidth=72
set colorcolumn=72

" Disable ruler in Cygwin environment. TODO Why did we do it?
if has("win32unix")
    set noruler
endif

" File navigation by Netrw
" REF: https://shapeshed.com/vim-netrw/
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_winsize = 20

" ===================================================================
" Plugins, including syntax highlighting and enhancement.
" ===================================================================
" All necessary plug-ins to support better editor experiences.
call plug#begin('~/.vim/bundle')

" Let's disable less used plug-ins for faster startup.
" =================================================================
" Plug 'elixir-lang/vim-elixir'
" Plug 'mattonrails/vim-mix'
" Plug 'derekwyatt/vim-scala'
" Plug 'udalov/kotlin-vim'
" Plug 'JuliaEditorSupport/julia-vim'
" Plug 'PProvost/vim-ps1'
" =================================================================
Plug 'rust-lang/rust.vim'
Plug 'fatih/vim-go'
Plug 'aklt/plantuml-syntax'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mechatroner/rainbow_csv'
" An bug: it always complains g:airline_statusline_funcrefs undefined.
let g:vaxe_enable_airline_defaults=0
Plug 'jdonaldson/vaxe'

" Let's change our live a bit: Enable LSP for C++. 
Plug 'yegappan/lsp'

" All themes below comes from 
" https://github.com/rafi/awesome-vim-colorschemes
" Below is what I tried and looks good. However, none of them works
" well on all four scenarios: vim (command line), nvim (command line),
" gvim (GUI), and nvim-qt (GUI).
"
" So eventually I fallback to default desert theme, though these themes
" are still installed.
"
" Surprisingly, most display issues come from vim for Windows
" (command line, non-Cygwin). Nvim works fine on almost all scenarios. 
" Plug 'ayu-theme/ayu-vim'
" Plug 'danilo-augusto/vim-afterglow'
" Plug 'ajmwagar/vim-deus'
" Plug 'liuchengxu/space-vim-dark'
" Plug 'rakr/vim-one'  -- vim-one: Tweak does not work. Don't use it.
Plug 'joshdick/onedark.vim'

" ===================================================================
" Syntax highlighting
" ===================================================================
" Must put syntax setting within, or vim will exit with code 1 when
" running hg commit. Reasons still unknown. Suggestion comes from
" pathogen Github page.
syntax on
filetype plugin indent on
call plug#end()

if !exists('g:GtkGuiLoaded') && !has("gui_running")
    " Set transparent background for console, but don't do it for
    " Neovim-GTK, as it results in a completely black background.
    au VimEnter * hi Normal guibg=NONE ctermbg=NONE
endif

" Support LSP
let clangdExe = '/usr/bin/clangd'
let rustAnalyzerExe = '/home/fuzhouch/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer'
if has("win32")
    let clangdExe = 'C:/Users/fuzhouch/scoop/shims/clangd.exe'
    let rustAnalyzerExe = 'C:/Users/fuzhouch/.rustup/toolchains/stable-x86_64-pc-windows-msvc/bin/rust-analyzer.exe'
endif
let lspServers = [
            \     #{
            \        filetype: ['c', 'cpp'],
            \        path: clangdExe,
            \        args: ['--background-index']
            \      },
            \     #{
            \	 filetype: ['rust'],
            \	 path: rustAnalyzerExe,
            \	 args: [],
            \        syncInit: v:true
            \      }
            \   ]
autocmd VimEnter * call LspAddServer(lspServers)
let lspOpts = {'autoHighlightDiags': v:true}
autocmd VimEnter * call LspOptionsSet(lspOpts)

" Color schemes
" I usually use only two themes, built-in desert and onedark. Onedark
" is usually used by default but sometimes I need a brighter color.
" Desert looks better in dark theme but needs a small modification to
" get a reasonable SpellBad look and feel. See below for switching.
" 
" I personally still love onedark theme, yet I really need torte for a
" comfortable eye-feelings under low screen blightness, especially for
" reading comments. Onedark has a nice color but constract is too low.
"
" So I tweak color of comments for better readability. The color settings
" here is copied from desert color scheme.
colorscheme onedark
highlight Normal guibg=#171421
highlight Comment term=bold ctermfg=11 guifg=#6DCEEB
let g:airline_theme="onedark"
let g:airline_powerline_fonts=0

" colorscheme desert
" let g:airline_theme="badwolf"

" ====================================================================
" Default file opening settings. Mostly for syntax highlighting.
" ====================================================================

" File open settings
" SCons
au BufEnter SConscript :set ft=python
" Objective-C++
au BufEnter *.mm :set ft=objc
" Elixir
au BufEnter *.exs :set ft=elixir
" Enable spell checking for text input
au BufEnter *.txt :setlocal spell spelllang=en_us
au BufEnter *.md :setlocal spell spelllang=en_us
au BufEnter *.rst :setlocal spell spelllang=en_us
au BufEnter *.md.txt :setlocal spell spelllang=en_us
au BufEnter *.rst.txt :setlocal spell spelllang=en_us

" A specific setting for nvim: Force disable foldmethod by expr
au BufEnter *.rst :setlocal foldmethod=manual

" All xml files set tab/indention to 2
au BufEnter *.xml :set shiftwidth=2
au BufEnter *.yaml :set shiftwidth=2
au BufEnter *.yml :set shiftwidth=2
au BufEnter *.json :set shiftwidth=2
" Golang - Make sure we meet go fmt requirements.
au BufNewFile,BufRead *.go set noexpandtab shiftwidth=8

" Below are my old Microsoft memory. Hope I can reuse them some day.
if has("win32")
    set selectmode="mouse,key"
    set keymodel="startsel,stopsel"
    set backspace=indent,eol,start whichwrap+=<,>,[,]
    au BufNewFile,BufRead *.cpp set makeprg=MSBuild.exe efm=%f(%l):\ %m
    au BufNewFile,BufRead *.c set makeprg=MSBuild.exe efm=%f(%l):\ %m
    au BufNewFile,BufRead *.cs set makeprg=MSBuild.exe efm=%f(%l):\ %m
    au BufNewFile,BufRead *.vbs set makeprg=cscript efm=%f(%l%m
    au BufNewFile,BufRead *.js  set makeprg=cscript efm=%f(%l%m
    au BufNewFile,BufRead *.wsf  set makeprg=cscript efm=%f(%l%m

    au BufNewFile,BufRead *.js  set cindent
    au BufNewFile,BufRead *.wsf set autoindent

    " ---- Setting for Visual studio 2005
    au BufNewFile,BufRead *.csproj set ft=xml
    au BufNewFile,BufRead *.csproj set fileencoding=utf8
    au BufNewFile,BufRead *.csproj set encoding=utf8
    au BufNewFile,BufRead *.csproj set fileencoding=utf8
    au BufNewFile,BufRead *.sln set encoding=utf8
    au BufNewFile,BufRead *.msh set filetype=msh
    au BufNewFile,BufRead *.sif set filetype=dosini

    " Razzle
    au BufNewFile,BufRead sources set filetype=make
    au BufNewFile,BufRead dirs set filetype=make

    " Powershell
    au BufEnter *.ps1 :set ft=ps1
    au BufEnter *.ps1 :set cindent

    " Settings for internal files. Not available outside Microsoft.
    au BufNewFile,BufRead *.script set ft=cosmos
    au BufNewFile,BufRead *.view set ft=cosmos

    " My hand written syntax highlighting for Bond file.
    " Find definition from https://github.com/Microsoft/bond
    au BufNewFile,BufRead *.bond set ft=bond

    if has("gui_running")
        set guifont=consolas:h11
    endif
endif
